"""task

Revision ID: 038af30f39f0
Revises: 9622f89d2236
Create Date: 2024-11-29 15:08:06.907373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038af30f39f0'
down_revision: Union[str, None] = '9622f89d2236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty_level',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_category',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_category',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['task_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=128), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('solution_url', sa.String(length=256), nullable=True),
    sa.Column('difficulty_level_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['task_category.id'], ),
    sa.ForeignKeyConstraint(['difficulty_level_id'], ['difficulty_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_image',
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['image_category.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_image')
    op.drop_table('task')
    op.drop_table('task_category')
    op.drop_table('image_category')
    op.drop_table('difficulty_level')
    # ### end Alembic commands ###
